workspace:
  base: /srv/drone-demo
  path: ./example

pipeline:
  build:
    image: golang:alpine
    pull: true
    # environment:
    #   - KEY=VALUE
    commands: 
    # - chmod +x /srv/drone-demo/example/command.sh
    # - /srv/drone-demo/example/command.sh
      - pwd
      - ls
      - date
      - go test ./go-example -coverprofile=coverage.out
  
  codecov:
    image: robertstettner/drone-codecov
    token: d8ed8d81-e443-4699-bd03-981b6f62e470
    files:
      - /srv/drone-demo/example/coverage.out

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: general
    when:
      status: [ success, failure ]