version: '3.5'
services:
  drone-server:
    image: drone/drone:latest
    container_name: drone_server
    ports:
      - 80:8000
      - 9000:9000
    volumes:
      - ./drone-data:/var/lib/drone/:rw
    restart: always
    environment:
      - DRONE_SECRET=drone
      - DRONE_OPEN=true
      - DRONE_GITHUB_URL=https://github.com
      - DRONE_HOST=http://10.0.1.12 # ${DRONE_HOST} # {scheme}://{ip} or {scheme}://{dns} 
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=0ac557124e7ed34a4cea #${DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=863c3bf5a2b5e1fe77c6bb07f1e6ef63f2f2d5c7 #${DRONE_GITHUB_SECRET}
    networks:
      - drone
networks:
  drone:
    name: drone