version: '3.5'
services:
  drone-agent:
    image: drone/agent:latest
    container_name: drone_agent
    restart: always
    # depends_on:
    #   - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - DOCKER_API_VERSION=1.24
      - DRONE_SECRET=drone # host secret
      - DRONE_SERVER=drone_server:9000 # {ip}:{port} or {dns}:{port} don't set {scheme}
      - DRONE_KEEPALIVE=6m
    networks:
      - drone
networks:
  drone:
    name: drone