version: '3'
services:
  drone-server:
    image: drone/drone:latest
    ports:
      - 80:8000
      - 9000:9000
    volumes:
      - ./drone-data:/var/lib/drone/:rw
    restart: always
    environment:
      - DRONE_SECRET=drone
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST} # {scheme}://{ip} or {scheme}://{dns} 
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}