version: '3'
services:
  drone-agent:
    image: drone/agent:latest
    restart: always
    # depends_on:
    #   - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - DRONE_SECRET=drone # host secret
      - DRONE_SERVER=:9000 # {ip}:{port} or {dns}:{port} don't set {scheme}
